
# Arrays in Python - python does not have built-in support for arrays. Lists can be used instead. 
# They have same properties of array - contiguous memory. O(1) access by index etc. Important to note that - only references are stored contiguously
# the actual values might be located anywhere in the memory. When Python List grows beyond memory what was allocated, a new memory block (usually twice the size of earlier) is allocated, 
# existing elements are copied to new block and old block is freed.
# arr = ["apple", "banana", "papaya"] # this is actually list
# iterate - for item in arr:
# arr.pop(1) # removes item at index 1
# arr.pop()  # removes last item
# arr.remove("apple") # removes first occurrence of item with value "apple"
# arr.append("pineapple") # adds item to the end
# other array/list operations - copy(), count(),len(arr), remove(), reverse(), sort(),index(<value>), insert(<index>, <value>), extend(<iterable>) etc.

def LargestEmement(arr): # O(n) time complexity, O(1) space complexity
    largest = arr[0]
    for indx,item in enumerate(arr):    
        if item > largest:
            largest = item
    return (largest,indx)


# assert(LargestEmement([1,2,3,4,5,6,7,8,9,10]) == (10,9)), "LargestEmement([1,2,3,4,5,6,7,8,9,10]) == (10,9) failed"
# assert(LargestEmement([-10,-20,-3,-4,-5,-6,-7,-8,-9,-1]) == (-1,9)), "LargestEmement([-10,-20,-3,-4,-5,-6,-7,-8,-9,-1]) == (-1,9) failed"
# assert(LargestEmement([5]) == (5,0)), "LargestEmement([5]) == (5,0) failed"


def SecondLargestElement(arr): # O(n) time complexity, O(1) space complexity
    assert(len(arr) >= 2), "Array must have at least two elements"
    largest = arr[0]
    secondLargest = None
    for item in arr:
        if largest is None or item > largest:
            secondLargest = largest
            largest = item
        elif (secondLargest is None or item > secondLargest) and item != largest:
            secondLargest = item
    return secondLargest

# assert(SecondLargestElement([1,2,3,4,5,6,7,8,9,10]) == 9), "SecondLargestElement([1,2,3,4,5,6,7,8,9,10]) == 9 failed"
# assert(SecondLargestElement([-10,-20,-3,-4,-5,-6,-7 ,-8,-9,-1]) == -3), "SecondLargestElement([-10,-20,-3,-4,-5,-6,-7,-8,-9,-1]) == -3 failed"
# assert(SecondLargestElement([5,5,5,5,5,5,5,10]) == 5), "SecondLargestElement([5,5,5,5,5,5,5,10]) == 5 failed"
# assert(SecondLargestElement([5,5,5,5,5,5,5]) == None), "SecondLargestElement([5,5,5,5,5,5,5]) == None failed"

def NthLargestElementSeemsNotEfficient(arr, n):
    # O(n log(n)) time complexity, O(n) space complexity - code generated by copilot - I think it should be O(n log(n)) since it uses sorting. I think 
    # we can do  O(n) since by implemeting array pivot on the nth element
    assert(len(arr) >= n and n > 0), "Array must have at least n elements and n must be positive"
    uniqueElements = set()
    for item in arr:
        uniqueElements.add(item)
    sortedUniqueElements = sorted(uniqueElements, reverse=True)
    if len(sortedUniqueElements) < n:
        return None
    return sortedUniqueElements[n-1]

# nth largest element in an array using quickselect algorithm - take random (middle) element from array & move it to its correct place in the array.
# Find its  correct place /'pivotindex' such that all elements to
# its left are greater than pivot and all elements to its right are less than pivot. 
# Check if the correctplace / pivotIndex == n-1 , if yes, we have found nth largest element. Else, the nth largest e;ement could lie on left or right side of the 
# array. Select the appropriate sidef and then  repeat the process. this goes on till   we find the nth largest element
# It is O(n) because we are looking at each element of the array only once (actually ~twice - N + N/2+N/4 ... = 2N). Each iteration reduces the number of elements to be looked at by ~half and we only look at one side and discard the other side..
def NthLargestElement(arr, n):
    # O(n) time complexity, O(1) space complexity (since it is inplace implementation) - using quickselect algorithm. Note quickselect works only on one side of pivot, while quicksort works on bth side of array since it has to sort entire array.of the array 
    assert(len(arr) >= n and n > 0), "Array must have at least n elements and n must be positive"
    # print(f"input array={arr}, nth ={n}")
    # if number of distinct elements are less than n, then return None
    if(len(set(arr)) < n): # python array/list to set is O(n) time complexity.. hence this function doe snto change the complexity of algorithm
        return None

    def partition(left, right, pivotIndex):
        
        pivotValue = arr[pivotIndex]
        # print("---------partition start-----------")
        # print(f"partition({left}, {right}, pivotIndex={pivotIndex},pivotValue={pivotValue}) ")
        # move pivot to end
        arr[pivotIndex], arr[right] = arr[right], arr[pivotIndex]
        storeIndex = left
        for i in range(left, right):
            if arr[i] > pivotValue: # note: '>' for nth largest
                arr[storeIndex], arr[i] = arr[i], arr[storeIndex] # swap to the left boundary that as all elements less value than  pivot element
                storeIndex += 1
        # move pivot to its final place
        arr[right], arr[storeIndex] = arr[storeIndex], arr[right] # now all elelements less than pivot value are towards its left and all elements greater than pivot value are towards its right
        # print(f"arr={arr}, newPivotIndex={storeIndex}")
        
        # print("---------partition  end-----------")
        return storeIndex  # index of the pivot such that all elements to its left are lesser than pivot value and all elements to its right are greater than pivot value

    left, right = 0, len(arr) - 1 #left is first element and right is last element
    pivotIndex = left + (right - left) // 2 # choosing middle element as pivot

    while pivotIndex>0 and pivotIndex<len(arr): # partition work looks at reducing number of array elements each iteration - is = N + N/2 + N/4 + ... = 2N = O(N)
        pivotIndex = left + (right - left) // 2 # choosing middle element as pivot
        pivotNewIndex = partition(left, right, pivotIndex) # the middle element has been placed at new index such that all elenments to its left are lesser and all elements to its right are greater
        if pivotNewIndex == -1:
            return None
        if pivotNewIndex == n - 1: # if new pivot is nth position then we have the answer
            # print("final array:", arr)
            # print("nth largest element index in final array:", pivotNewIndex)

            return arr[pivotNewIndex]
        elif pivotNewIndex < n - 1: # if new pivot index is less than nth position, we need to search in right half
            if pivotNewIndex + 1 > right:
                return None
            left = pivotNewIndex + 1
        else:
            if pivotNewIndex - 1 < left:
                return None
            right = pivotNewIndex - 1 # if new pivot index is greater than nth position, we need to search in left half
    return None


# assert(NthLargestElement([1,2,3,4,5,6,7,8,9,10], 3) == 8), "NthLargestElement([1,2,3,4,5,6,7,8,9,10], 3) == 8 failed"
# assert(NthLargestElement([-10,-20,-3,-4,-5,-6,-7,-8,-9,-1], 4) == -5), "NthLargestElement([-10,-20,-3,-4,-5,-6,-7,-8,-9,-1], 4) == -4 failed"
# assert(NthLargestElement([5,5,5,5,5,5,5,10], 2) == 5), "NthLargestElement([5,5,5,5,5,5,5,10], 2) == 5 failed"
# assert(NthLargestElement([5,5,5,5,5,5,5,10], 1) == 10), "NthLargestElement([5,5,5,5,5,5,5,10], 1) == 10 failed"
# assert(NthLargestElement([5,5,5,5,5,5,5,10], 3) == None), "NthLargestElement([5,5,5,5,5,5,5,10], 1) == None failed"
# assert(NthLargestElement([5,5,5,5,5,5,5], 2) == None), "NthLargestElement([5,5,5,5,5,5,5], 2) == None failed"

def IsArraySorted(arr): # O(n) time complexity, O(1) space complexity - determines if array is either sorted ascending or sorted descending
    assert(len(arr) > 0), "Array must have at least one element"
    arrIsAscending = False
    arrIsDescending = False
    orderSet = False
    for i in range(1,len(arr)):
        if not orderSet:
            if arr[i] < arr[i-1] and orderSet == False:
                arrIsAscending = True
                orderSet = True
            if arr[i] > arr[i-1] and orderSet == False:
                arrIsDescending = True
                orderSet = True
        if orderSet == True:
            if arr[i] > arr[i-1] and arrIsAscending == True: # first adjacent non-equal element resulted in descending order. Current adjacent elements are in ascending order.
                return False
            if arr[i] < arr[i-1] and arrIsDescending == True: # first adjacent non-equal element resulted in descending order. Current adjacent elements are in ascending order.
                return False
    return True

# assert(IsArraySorted([1,2,3,4,5,6,7,8,9,10]) == True), "IsArraySorted([1,2,3,4,5,6,7,8,9,10]) == True failed"
# assert(IsArraySorted([10,9,8,7,6,5,4,3,2,1]) == True), "IsArraySorted([10,9,8,7,6,5,4,3,2,1]) == True failed"
# assert(IsArraySorted([1,2,3,5,4,6,7,8,9,10]) == False), "IsArraySorted([1,2,3,5,4,6,7,8,9,10]) == False failed"
# assert(IsArraySorted([10,9,8,6,7,5,4,3,2,1]) == False), "IsArraySorted([10,9,8,6,7,5,4,3,2,1]) == False failed"
# assert(IsArraySorted([1,1,1,1,1,1,1]) == True), "IsArraySorted([1,1,1,1,1,1,1]) == True failed"


def ReverseArrayInPlace(arr): # O(n) time complexity, O(1) space complexity - reverses the array in place
    n = len(arr)
    for iter in range(n//2):
        # print(f"swapping arr[{iter}]={arr[iter]} and arr[{n - iter -1}]={arr[n - iter -1]}")
        arr[iter], arr[n-iter-1] = arr[n-iter-1], arr[iter]
    return arr

# assert(ReverseArrayInPlace([1,2,3,4,5]) == [5,4,3,2,1]), "ReverseArrayInPlace([1,2,3,4,5]) == [5,4,3,2,1] failed"
# assert(ReverseArrayInPlace([1,2,3,4,5,6]) == [6,5,4,3,2,1]), "ReverseArrayInPlace([1,2,3,4,5,6]) == [6,5,4,3,2,1] failed"


def MoveZerosToTheEnd(arr):
    zeroIndex = None
    #print(f"source array: {arr}")
    for iter in range(len(arr)):
        if zeroIndex is None:
            if arr[iter] == 0:
                zeroIndex = iter
            else:
                continue # move to next iteration
        if arr[iter] !=0:
            arr[zeroIndex], arr[iter] = arr[iter], arr[zeroIndex]
            zeroIndex += 1 # the non-zero one will be always the first one after current zero or all the next zeros
    #print(f"response  array: {arr}")
    return arr

# assert(MoveZerosToTheEnd([0,1,0,3,12]) == [1,3,12,0,0]), "MoveZerosToTheEnd([0,1,0,3,12]) == [1,3,12,0,0] failed"
# assert(MoveZerosToTheEnd([0,0,1]) == [1,0,0]), "MoveZerosToTheEnd([0,0,1]) == [1,0,0] failed"

def CounterClockWiseRotate(arr): # O(n) time complexity, O(1) space complexity - rotates the array counter clockwise by one position
    # print(f"source array: {arr}")
    assert(len(arr) > 0), "Array must have at least one element"
    n = len(arr)
    temp = arr[0]
    for iter in range(1, n):
        # print(f"sending arr[{iter}]={arr[iter]} to arr[{iter-1}]={arr[iter-1]}")
        arr[iter-1] = arr[iter]
    arr[n-1]= temp
    # print(f"response  array: {arr}")
    return arr

#assert(CounterClockWiseRotate([1,2,3,4,5]) == [2,3,4,5,1]), "CounterClockWiseRotate([1,2,3,4,5]) == [2,3,4,5,1] failed"
#assert(CounterClockWiseRotate([5,4,3,2,1]) == [4,3,2,1,5]), "CounterClockWiseRotate([5,4,3,2,1]) == [4,3,2,1,5] failed"

def CounterClockWiseRotateBymSpaces(arr,m): # O(n) runtime complexity and O(1) space complexity
    temp = arr[-m:]
    # print(f"temp={temp},arr={arr}")
    n = len(arr)
    for iter in range(n-m):
        arr[iter-m] = arr[iter]
    tmp=0
    for iter1 in range(n-m,n):
        #print(f"iter1-m={iter1-m}, iter1={iter1}")
        arr[iter1-m] = temp[tmp]
        tmp+=1
    #print(f"response  array: {arr}")
    return arr

#assert(CounterClockWiseRotateBymSpaces([1,2,3,4,5,6,7,8],3) == [4,5,6,7,8,1,2,3])
#assert(CounterClockWiseRotate([5,4,3,2,1]) == [4,3,2,1,5]), "CounterClockWiseRotate([5,4,3,2,1]) == [4,3,2,1,5] failed"

'''
leader in an array (sorted or unsorted) is a number which does not have anything greater than it on right of the array.
Ex - for array [7,10,4,3,6,5,2] the answer is 10,6,5,2
Ruick solution I could think of  -  traverse from end of array noting the greatest number hit so far ('greatest_so_far'). 
If current number is greater than the greatest_so_far then it belongs to the answer. and greatest_so_far becomes current number
'''
def PrintLeadersInAnArray(arr): 
    n = len(arr)
    greatest_so_far = arr[n-1]
    response = []
    response.append(greatest_so_far)
    for y in reversed(range(n-1)):
        if arr[y]>=greatest_so_far:
            response.append(arr[y])
            greatest_so_far = arr[y]
    response.reverse()
    # print(f"response  array: {response}")
    return response

# assert(PrintLeadersInAnArray([7,10,4,3,6,5,2]) == [10,6,5,2])
# assert(PrintLeadersInAnArray([10,20,30]) == [30])
# assert(PrintLeadersInAnArray([30,20,10]) == [30,20,10])


'''
find a pair (i,j) such that arr[j]-arr[i] is maximmum possible where j>i
first plan - keep track of lowest_number (i) so far and keep track of max_difference (evaluate at each cell) with the lowest_number. Also update j at the max_difference.
If at any cell, the number is lower than lowest_number then update the lowest_number/j as that cells number/index. Going forward use that lowest_number
to diff with next cell values. At each diff check if that diff is > max_difference. If yes, then update that max_difference/j to new value/index.
When reaching the end of the array the max_difference is the best you can get and (i,j) is teh cells at which maximum difference is got.
'''        
def MaxDiff(arr):
    i = 0
    #print(f"arry={arr}")
    n = len(arr)
    if n==2:
        return 0 if arr[1]-arr[0] <0 else arr[1]-arr[0] 
    j = None if arr[0]>arr[1] else 1
    l = arr[0] if arr[0]<arr[1] else arr[1] # l = lowest array value
    

    mv = arr[1]-arr[0] if arr[1]>arr[0] else 0 # mv = maximum value
    for y in range(2,n):
        if arr[y]-l > mv:
            mv = arr[y]-l # new high point wrt current low point
            j = y
        if arr[y]<l:
            l = arr[y] # new low point which will be the reference for future difference
            i = y
            j = None
        #print(f"index={y},i={pi if j is None else i},j={pj if j is None else j},max value={mv},lowest element={l}")
    return mv

# assert(MaxDiff([2,3,10,6,4,8,1]) == 8)
# assert(MaxDiff([7,9,5,6,3,2]) == 2)
# assert(MaxDiff([10,20,30]) == 20)


def FrequenciesOfNumbersInUnsortedArray(arr):
    n = len(arr)
    response = {}
    for y in range(n):
      if arr[y] in response:
        response[arr[y]] += 1
      else:
        response[arr[y]] = 1
    return response    
# assert(FrequenciesOfNumbersInUnsortedArray([10,25,10,30,10,30])=={10:3, 25:1, 30:2})
# assert(FrequenciesOfNumbersInUnsortedArray([10,10,10,10])=={10:4})
# assert(FrequenciesOfNumbersInUnsortedArray([30,10,20])=={10:1, 20:1, 30:1})

def FrequenciesOfNumbersInSortedArray(arr):
    n = len(arr)
    assert(n>0)
    freq = []
    if n==1:
        freq.append(1)
        return freq
    tmp = 1
    
    for y in range(1,n):
      if arr[y-1] != arr[y]:
        freq.append(tmp)
        tmp = 1
      else:
        tmp += 1
    freq.append(tmp)
    return freq   

# assert(FrequenciesOfNumbersInSortedArray([10])==[1])
# assert(FrequenciesOfNumbersInSortedArray([10,10,10,25,30,30])==[3, 1, 2])
# assert(FrequenciesOfNumbersInSortedArray([10,10,10,10])== [4])
# assert(FrequenciesOfNumbersInSortedArray([10,20,30])==[1,1,1])

'''
Maximize the profit (buy on one day and sell on any other following day and can repeat this buy-sell process) given prices of stock each day for 'n' days.
plan - buy at point before it goes up and sell at highest point before it goes down.
'''
def BuyAndSellStock(prices):
    profit = 0
    n = len(prices)
    l = prices[0]
    h = None
    for y in range(1, n):
        if h is None: # we are at second cell (or) just going on an down trend
            if prices[y] <= l:
                l = prices[y]
                #print(f"now l={l}")
            else: # just started upward trend
                h = prices[y]
                #print(f"started upward trend after l={l}, now h={h}")
        else: # we are on upward trend
            if prices[y] >= h:
                h = prices[y]
                #print(f"now h={h}")
            else: # just started downward trend
                profit += h-l # get profit till previous high
                l = prices[y]
                #print(f"started downward trend after {h}, profit = {profit}, l = {l}")
                h = None
    if h != None: # last point was the highest
        profit += h-l
    return profit

# assert(BuyAndSellStock([1,5,3,8,12]) == 13)
# assert(BuyAndSellStock([30,20,10]) == 0)
# assert(BuyAndSellStock([10,20,30]) == 20)
# assert(BuyAndSellStock([1,5,3,1,2,8]) == 11)

'''
Maximize the profit (buy on one day and sell on any other following day and can repeat this buy-sell process) given prices of stock each day for 'n' days.
simplier plan - when the stock price goes up add the difference of prviousprice and current price to profit
'''
def BuyAndSellStockSimple(prices):
    n = len(prices)
    profit = 0
    for y in range(1, n):
        if prices[y]>prices[y-1]:
            profit += prices[y]-prices[y-1]
    return profit


# assert(BuyAndSellStockSimple([1,5,3,8,12]) == 13)
# assert(BuyAndSellStockSimple([30,20,10]) == 0)
# assert(BuyAndSellStockSimple([10,20,30]) == 20)
# assert(BuyAndSellStockSimple([1,5,3,1,2,8]) == 11)

'''
Given a array of non-negative integers representing heights of bars, how much maximum water can you collect between them?
plan - assume that bar width is 1. height changes from one bar to another. note down start and end of troughs in one pass of the array (can do this by noting start as bar from which downward trend started and end of trough
as the bar after which next downward trend starts). end result of this pass = [(start_index,end_index)]
next pass of the array - for all bars from start+1 to end-1, vol += (|start-end|-current_bar_height)*1
'''
def MaximumRainWater(arr):
    n = len(arr)
    start = None
    end = None
    upward = None
    troughs = []
    for y in range(1,n):
        if arr[y-1] > arr[y] and start==None: # downward trend
            start = y-1
        elif arr[y-1] < arr[y] and start!=None:
            upward = 1 # upward trend of trough started
            if y == n-1: # this is last element after upward trend started
                end = y
                troughs.append((start,end))
        elif arr[y-1] > arr[y] and start!=None and upward!=None: # next downward trend started => trough is between first downward index and y-1
            end = y-1
            upward = None
            troughs.append((start,end))
            start = end
    vol = 0
    #print(troughs)
    for trough in troughs:
        ht = min(arr[trough[0]],arr[trough[1]]) # height of container formed by the trough
        # print(f"ht={ht}")
        for y in range(trough[0]+1,trough[1]): # ignore the start and end bard of trough
            assert((ht-arr[y])>0) # debug assertion that checks that all bars in a trough are lesser height than the height difference of ends of trough
            vol += ((ht-arr[y])*1)
    return vol

#assert(MaximumRainWater([2,0,2])==2)
#assert(MaximumRainWater([3,0,1,2,5])==6)

'''
given a array, find subarray (contiguous elements of array) with maximum sum

'''
def MaximumSubarraySum(arr):
    n = len(arr)
    max_total_current = arr[0]
    max_total = max_total_current
    for y in range(1,n):
        # print(f"max_total={max_total}")
        max_total_current = max(arr[y], max_total_current+ arr[y])
        max_total = max(max_total,max_total_current)
    #print(f"max_total={max_total}")
    return max_total

#assert(MaximumSubarraySum([2,3,-8,7,-1,2,3])==11)
#assert(MaximumSubarraySum([5,8,3])==16)
#assert(MaximumSubarraySum([-6,-1,-8])==-1)

'''
Get the subarray that has minimum sum
'''
def MinimumSubarraySum(arr):
    n = len(arr)
    min_total_current = arr[0]
    min_total = min_total_current
    for y in range(1,n):
        # print(f"min_total={min_total}")
        min_total_current = min(arr[y], min_total_current+ arr[y])
        min_total = min(min_total,min_total_current)
    # print(f"min_total={min_total}")
    return min_total

'''
Given an array, find length of  maximum sum subarray such that the subaray elements are alternating even odd elements. Specialization of
normal maximum sum subarray problem.
'''
def MaxSumSubArrayWithEvenOddAlternating(arr):
    n = len(arr)
    max_total_current = arr[0]
    max_total = max_total_current
    max_total_index = 0

    def ElementsAreNotSameType(y1,y2):
        return (y1%2==0 and (not y2%2==0)) or ((not y1%2==0) and y2%2==0)

    for y in range(1,n):
        if ElementsAreNotSameType(arr[y],arr[y-1]):
            max_total_current = max(max_total_current, max_total_current+arr[y])
        else: # current element breaks even odd pattern => cannot consider total given by (y-1)the element
            max_total_current = arr[y]
        if max_total<max_total_current:
            max_total = max_total_current
            max_total_index = y
        # print(f"y={y}, max_total={max_total},max_total_current={max_total_current},max_total_index={max_total_index}")
        total_tmp = max_total
        index_tmp = max_total_index-n
        lenght_of_max_array=0
        while total_tmp!=0:
            total_tmp -= arr[index_tmp];
            index_tmp -= 1
            lenght_of_max_array += 1

    return lenght_of_max_array

#assert(MaxSumSubArrayWithEvenOddAlternating([10,12,14,7,8])==3)
#assert(MaxSumSubArrayWithEvenOddAlternating([7,10,13,14])==4)
#assert(MaxSumSubArrayWithEvenOddAlternating([10,12,8,4])==1)

'''
circular subarray include normal subarray + the subarrays formed by connecting last element of array to the first element.
plan - create new array [1,2,..n-1,0,1,...n-1]. 
0th element suffix array if from previous 1 element
1st element suffix array is from preious 2nd element 
and so on ...
ex - [0,1,2,3] is source array. modified array = [1,2,3,0,1,2,3]
while calculating max suffix array for each element from 1,n-1, we store the length of max suffix array as well.
for calculating the max suffix array of ith element -
we consider if length of previous element suffix array is n. If it is, then we have to substract  the value of nthe element from previous elements
max suffix array to get the new max suffix array to use for i+1th element.

current_max[i+1] = 
if len(max suffix array of ith element)==n: # remove the i-nth element since it is same as i+1 th element
    max(arr[i+1],arr[i+1]+current_max[i]-arr[i-n])
else:
    max(arr[i+1],arr[i+1]+current_max[i])

'''
def MaximumCircularSumSubarray(arr):
    n = len(arr)
    max_sum_original = MaximumSubarraySum(arr)
    # print(f"arr={arr}")
    # maximum sub array of circular for of arr, which is circular array = total sum of all elements of arr - (minimum sum subarray of arr)
    max_sum_circular = sum(arr) - MinimumSubarraySum(arr)
    return max(max_sum_original, max_sum_circular)

#assert(MaximumCircularSumSubarray([5,-2,3,4])== 12)
#assert(MaximumCircularSumSubarray([2,3,-4])== 5)
#assert(MaximumCircularSumSubarray([8,-4,3,-5,4])== 12)
#assert(MaximumCircularSumSubarray([-3,4,6,-2])== 10)
#assert(MaximumCircularSumSubarray([3,-4,5,6,-8,7])== 17)

'''
Majority element in an array is element that appears > n/2 times. Return majority element in 
given array if it exists
first plan - O(n log(n)) algorithm is easy. Sort the array which is O(n log(n)). 
Next iterate over all elements of array O(n) noting the element that has maximum frequency.
If the max_frequency > n/2 return that element .. else return None
Next thought improvement O(n) runtime - why not use hash table - in O(n) pass it will store frequencies of all the elements .. and
when I am updating the frequency of particular element, keep the count of max_frqeuency_so_far and corresponding element.

'''
def MajorityElement(arr):
    f = {}
    n = len(arr)
    max_freq = 0
    for i in range(n):
        v = arr[i]
        if v in f:
            f[v] += 1
        else:
            f[v] = 1
        if f[v]>max_freq:
            max_freq = f[v]
            elem = v
    return elem if max_freq > n//2 else None
            
# assert(MajorityElement([8,3,4,8,8])==8)
# assert(MajorityElement([3,7,4,7,7,5])==None)

'''
Make all elements of given binary array same by flipping all 0's to 1's or viceversa (one of of these is allowed)
When flipping, you can flip consecutive 0's and 1's together. 
Find mimimum number of flips required to make array elements all same and print those flips.
plan - find count of islands of o's and count of islands of 1 and choose to flip the 
one with lesser islands.
Even mroe optimised solution - If you observe patterns in input/solution, you wil see that you just need to find the number that
is the 'first change' in array and then replace all islands that correspond to this number. This means islans field used in algorithm is not required.
'''
def MinimumNumberOfFlips(arr):
    n = len(arr)
    start_indices = ["",""]
    islands = [0,0] # counts of islands for 0's and for 1's
    prev = None
    for y in range(n):
        if not prev==arr[y]:
            islands[arr[y]] += 1 
            start_indices[arr[y]] += "," + str(y)
    response = start_indices[0] if islands[0]>islands[1] else start_indices[0]
    print(f"response={response[1:]}")
    return response[1:]

# assert(MinimumNumberOfFlips([1,1,0,0,0,1])=="2,3,4")
# assert(MinimumNumberOfFlips([1,0,0,0,1,0,0,1,1,1,1])=="1,2,3,5,6")
# assert(MinimumNumberOfFlips([1,1])=="")
# assert(MinimumNumberOfFlips([0,1])=="0")

'''
From all the ksized subarrays find the one with maximum sum.
plan - there will be n-k+1 totals to be compared.tart iterating through element. keep running_total in one variable and response_total in another variable.
Keep another variable start_index. While moving through the array (y in range(n)) keep adding numbers to running_total while 
  (y-start_index) <= k. At end, check response_total =  max(response_total, running_total). After reaching k, we add yth element
  to running_total and substract y-k th element from runnign total and at each iteration response_total =  max(response_total, running_total).
  At end of array return response_total =  max(response_total, running_total).
This is sliding window technique. We use the result from previous window in calculation of result of current window to get
performance optimzation.
'''
def MaxSubArrayOfSize(arr, k):
    n = len(arr)
    rt = 0 # running total
    t = 0 # max total
    for y in range(n):
        if y<k:
            rt += arr[y]
        else:
            t = max(t,rt) #previous sliding window
            rt += arr[y]
            rt -= arr[y-k]
    t = max(t,rt) # for kth sliding window ending in last element of arr
    return  t
            

# assert(MaxSubArrayOfSize([1,8,30,-5,20,7],3)==45)
# assert(MaxSubArrayOfSize([5,-10,6,90,3],2)==96)

'''
Find if any subarray exists with elements totaling to given total.
plan - set marker=0,running_total=0. while(y< (len(arrNonNegative))),keep adding arr+ay numbers to running_total and when it exceeds
target_total, substract the number at arr NonNegative[marker]. If the running_total is > target_total, marker++ and 
substract arrNonNegative[marker] from running_total. Keep doing this until running_total<target_total or end of array or marker==y or runnig_total==target_total (here we exit with 1 result).
Essentially we are removing elements from the running_total that if NOT will cause the running_total to always exceed 
target_total going forward. If marker reached 'y' then the curent subarray will not have any numbers adding to target_total and y goes to next iteration.
if after removing one or more numbers running_total<target_total then y++ and go through same logic
instructors approach -variable size window sliding technique is used. You shrink the window by increasing its starting point and icnrease the window size
by increasing the endpoint
arr = arrNonNegative
tar = target_total
'''
def SubarrayWithGivenSum(arr,tar):
    s=0
    e=0
    n = len(arr)
    r = 0 # running total
    while e<n:
        r += arr[e]
        if r == tar:
            return 1
        if r>tar: # substract numbers from start of window
            while r>tar and e>s:
                r -= arr[s]
                s += 1
            e += 1
    return 0

# assert(SubarrayWithGivenSum([1,4,20,3,10,5],33)==1)
# assert(SubarrayWithGivenSum([1,4,0,0,3,10,5],7)==1)
# assert(SubarrayWithGivenSum([2,4],3)==0)


'''
Given one array of numbers we need to find sum of elements from start index to end index in O(1)
This is solved using prefix sum technique ( lot of puzzles this will help). prefix sum of of element 
at ith index = sum of all element from 0  to i
plan - First pre compute prefix sum of all the elements of the array in O(n) time
(just iterate and add elements)- store these in ps[n]. Then
FindSum(l,r) is given by = ps[r]-ps[l-1] for l!=0 and ps[r] for l==0

if l=0 then ps[r] else ( if (l==r) ps[r]-ps[r-1] else ps[r]-ps[l-1])
requirement is hazy - [l,r] means sum including both l and r or excluding l and including r ?
'''
def FindSum(arr,ranges):# ranges = [[s1,e1],[s2,e2],[s3,e3]] where s_= start index,e_ = end index
    # for each array number, calculate all prefix array  (sub arrays that start at that array element) sums
    tmp = 0
    n = len(arr)
    ps = [] # prefix sum array
    # ps = [tmp := tmp + x for x in arr]
    for y in range(n):
        tmp += arr[y]
        ps.append(tmp)
    
    # tmp = 0
    # ps = [tmp := tmp + x for x in arr] # list comprehension way to create prefix sum array
    res = [ps[range[1]] if range[0]==0 else ( (ps[range[1]]-ps[range[1]-1]) if (range[1]==range[0]) else ps[range[1]]-ps[range[0]]) for range in ranges ]
    print(res, ranges[0][1], ranges[0][0])
    return res

#assert(FindSum([1,2,3],[[1,1]])==[2])
#assert(FindSum([1,2,3],[[0,0],[0,1],[0,2],[1,1],[1,2],[2,2]])==[1,3,6,2,5,3])

'''
given 2 arrays {max 100000 elements, each of which can have value between [0,100]} which correspond to start of range, end of range, find out any one element appears in most of the ranges

plan - if s array is  sorted  - go through numbers of both arrays in ascending order, and increment 
temporary variable 'tmp' each time start array element  is encountered (the start element will get overlap value as the number 'tmp' at that stage)
 and decrement it each time end range element is encountered. Note max element and max time each time any start element is encountered.
 When you reach end of all ranges you will have the number that has most overlap (as well as number of times it overlapped)


'''
def FindMaximumAppearingELement(s, e): # s = start range array, e = end range array
    n = len(s) 
    p = s[0] # current point
    tmp = 1 # matching ranges
    si = 1 # index in sra
    ei = 0 # index in era
    t = 1  # maximum so far
    a = s[0] # answer =  element that occurs in maximum ranges
    while si<n :
        if s[si]<=e[ei]: # next in line is start of a range
            tmp += 1 
            if t < tmp:
                t = tmp
                a = s[si]
            si += 1
        else: # next in line is end of a range
            tmp -= 1
            ei += 1
    return a

# assert(FindMaximumAppearingELement([1,2,5,15],[5,8,7,18])==5)
# assert(FindMaximumAppearingELement([1,2],[5,4])==2)

'''
equilibrium point in an array is any element (if it exists) such that sum of elements on its left side and sum of elements on its right side is the same.
For elements at start and end of array, sum at the ends can be assumed to be 0.
O(n) plan - calculate prefix sum array for all elements which is O(n). calculate suffix sum array for all elemetns of array  which is O(n). Third iteration
go through each element and check if elements prefix sum and suffix sum are the same  which is O(n).
Another approach is calculate and keep total_sum. start from 0th element and keep increasing left sum (adding on previous left sum) and right sum will be (total_sum-current_left_sum)
'''
def EquilibriumPoint(arr):
    return 1

'''
For given array, can you divide it into 3 partitions such that all partitions total to the same value.

plan - total the numbers and see if it is multiple of 3. If no, return 0. If yes, then get the total that three parts should be = total/3.
Now we need to get 3 partitions of array each of which total to expected sum. one of these partitions starts from 0, while other partition ends at n-1. 
Calculate prefix and suffix arrays. Go through them to get 
indexes that total to given sum. The prefix array will give left most partition and suffix array will give right most partition. 
Third partition is between these 2 already found out arrays.
'''
def DoesThreePartitionsWIthEqualSumExist(arr):
    return 1
