
# Arrays in Python - python does not have built-in support for arrays. Lists can be used instead. 
# They have same properties of array - contiguous memory. O(1) access by index etc. Important to note that - only references are stored contiguously
# the actual values might be located anywhere in the memory. When Python List grows beyond memory what was allocated, a new memory block (usually twice the size of earlier) is allocated, 
# existing elements are copied to new block and old block is freed.
# arr = ["apple", "banana", "papaya"] # this is actually list
# iterate - for item in arr:
# arr.pop(1) # removes item at index 1
# arr.pop()  # removes last item
# arr.remove("apple") # removes first occurrence of item with value "apple"
# arr.append("pineapple") # adds item to the end
# other array/list operations - copy(), count(),len(arr), remove(), reverse(), sort(),index(<value>), insert(<index>, <value>), extend(<iterable>) etc.

def LargestEmement(arr): # O(n) time complexity, O(1) space complexity
    largest = arr[0]
    for indx,item in enumerate(arr):    
        if item > largest:
            largest = item
    return (largest,indx)


# assert(LargestEmement([1,2,3,4,5,6,7,8,9,10]) == (10,9)), "LargestEmement([1,2,3,4,5,6,7,8,9,10]) == (10,9) failed"
# assert(LargestEmement([-10,-20,-3,-4,-5,-6,-7,-8,-9,-1]) == (-1,9)), "LargestEmement([-10,-20,-3,-4,-5,-6,-7,-8,-9,-1]) == (-1,9) failed"
# assert(LargestEmement([5]) == (5,0)), "LargestEmement([5]) == (5,0) failed"


def SecondLargestElement(arr): # O(n) time complexity, O(1) space complexity
    assert(len(arr) >= 2), "Array must have at least two elements"
    largest = arr[0]
    secondLargest = None
    for item in arr:
        if largest is None or item > largest:
            secondLargest = largest
            largest = item
        elif (secondLargest is None or item > secondLargest) and item != largest:
            secondLargest = item
    return secondLargest

# assert(SecondLargestElement([1,2,3,4,5,6,7,8,9,10]) == 9), "SecondLargestElement([1,2,3,4,5,6,7,8,9,10]) == 9 failed"
# assert(SecondLargestElement([-10,-20,-3,-4,-5,-6,-7 ,-8,-9,-1]) == -3), "SecondLargestElement([-10,-20,-3,-4,-5,-6,-7,-8,-9,-1]) == -3 failed"
# assert(SecondLargestElement([5,5,5,5,5,5,5,10]) == 5), "SecondLargestElement([5,5,5,5,5,5,5,10]) == 5 failed"
# assert(SecondLargestElement([5,5,5,5,5,5,5]) == None), "SecondLargestElement([5,5,5,5,5,5,5]) == None failed"

def NthLargestElementSeemsNotEfficient(arr, n):
    # O(n log(n)) time complexity, O(n) space complexity - code generated by copilot - I think it should be O(n log(n)) since it uses sorting. I think 
    # we can do  O(n) since by implemeting array pivot on the nth element
    assert(len(arr) >= n and n > 0), "Array must have at least n elements and n must be positive"
    uniqueElements = set()
    for item in arr:
        uniqueElements.add(item)
    sortedUniqueElements = sorted(uniqueElements, reverse=True)
    if len(sortedUniqueElements) < n:
        return None
    return sortedUniqueElements[n-1]

# nth largest element in an array using quickselect algorithm - take random (middle) element from array & move it to its correct place in the array.
# Find its  correct place /'pivotindex' such that all elements to
# its left are greater than pivot and all elements to its right are less than pivot. 
# Check if the correctplace / pivotIndex == n-1 , if yes, we have found nth largest element. Else, the nth largest e;ement could lie on left or right side of the 
# array. Select the appropriate sidef and then  repeat the process. this goes on till   we find the nth largest element
# It is O(n) because we are looking at each element of the array only once (actually ~twice - N + N/2+N/4 ... = 2N). Each iteration reduces the number of elements to be looked at by ~half and we only look at one side and discard the other side..
def NthLargestElement(arr, n):
    # O(n) time complexity, O(1) space complexity (since it is inplace implementation) - using quickselect algorithm. Note quickselect works only on one side of pivot, while quicksort works on bth side of array since it has to sort entire array.of the array 
    assert(len(arr) >= n and n > 0), "Array must have at least n elements and n must be positive"
    # print(f"input array={arr}, nth ={n}")
    # if number of distinct elements are less than n, then return None
    if(len(set(arr)) < n): # python array/list to set is O(n) time complexity.. hence this function doe snto change the complexity of algorithm
        return None

    def partition(left, right, pivotIndex):
        
        pivotValue = arr[pivotIndex]
        # print("---------partition start-----------")
        # print(f"partition({left}, {right}, pivotIndex={pivotIndex},pivotValue={pivotValue}) ")
        # move pivot to end
        arr[pivotIndex], arr[right] = arr[right], arr[pivotIndex]
        storeIndex = left
        for i in range(left, right):
            if arr[i] > pivotValue: # note: '>' for nth largest
                arr[storeIndex], arr[i] = arr[i], arr[storeIndex] # swap to the left boundary that as all elements less value than  pivot element
                storeIndex += 1
        # move pivot to its final place
        arr[right], arr[storeIndex] = arr[storeIndex], arr[right] # now all elelements less than pivot value are towards its left and all elements greater than pivot value are towards its right
        # print(f"arr={arr}, newPivotIndex={storeIndex}")
        
        # print("---------partition  end-----------")
        return storeIndex  # index of the pivot such that all elements to its left are lesser than pivot value and all elements to its right are greater than pivot value

    left, right = 0, len(arr) - 1 #left is first element and right is last element
    pivotIndex = left + (right - left) // 2 # choosing middle element as pivot

    while pivotIndex>0 and pivotIndex<len(arr): # partition work looks at reducing number of array elements each iteration - is = N + N/2 + N/4 + ... = 2N = O(N)
        pivotIndex = left + (right - left) // 2 # choosing middle element as pivot
        pivotNewIndex = partition(left, right, pivotIndex) # the middle element has been placed at new index such that all elenments to its left are lesser and all elements to its right are greater
        if pivotNewIndex == -1:
            return None
        if pivotNewIndex == n - 1: # if new pivot is nth position then we have the answer
            # print("final array:", arr)
            # print("nth largest element index in final array:", pivotNewIndex)

            return arr[pivotNewIndex]
        elif pivotNewIndex < n - 1: # if new pivot index is less than nth position, we need to search in right half
            if pivotNewIndex + 1 > right:
                return None
            left = pivotNewIndex + 1
        else:
            if pivotNewIndex - 1 < left:
                return None
            right = pivotNewIndex - 1 # if new pivot index is greater than nth position, we need to search in left half
    return None


# assert(NthLargestElement([1,2,3,4,5,6,7,8,9,10], 3) == 8), "NthLargestElement([1,2,3,4,5,6,7,8,9,10], 3) == 8 failed"
# assert(NthLargestElement([-10,-20,-3,-4,-5,-6,-7,-8,-9,-1], 4) == -5), "NthLargestElement([-10,-20,-3,-4,-5,-6,-7,-8,-9,-1], 4) == -4 failed"
# assert(NthLargestElement([5,5,5,5,5,5,5,10], 2) == 5), "NthLargestElement([5,5,5,5,5,5,5,10], 2) == 5 failed"
# assert(NthLargestElement([5,5,5,5,5,5,5,10], 1) == 10), "NthLargestElement([5,5,5,5,5,5,5,10], 1) == 10 failed"
# assert(NthLargestElement([5,5,5,5,5,5,5,10], 3) == None), "NthLargestElement([5,5,5,5,5,5,5,10], 1) == None failed"
# assert(NthLargestElement([5,5,5,5,5,5,5], 2) == None), "NthLargestElement([5,5,5,5,5,5,5], 2) == None failed"

def IsArraySorted(arr): # O(n) time complexity, O(1) space complexity - determines if array is either sorted ascending or sorted descending
    assert(len(arr) > 0), "Array must have at least one element"
    arrIsAscending = False
    arrIsDescending = False
    orderSet = False
    for i in range(1,len(arr)):
        if not orderSet:
            if arr[i] < arr[i-1] and orderSet == False:
                arrIsAscending = True
                orderSet = True
            if arr[i] > arr[i-1] and orderSet == False:
                arrIsDescending = True
                orderSet = True
        if orderSet == True:
            if arr[i] > arr[i-1] and arrIsAscending == True: # first adjacent non-equal element resulted in descending order. Current adjacent elements are in ascending order.
                return False
            if arr[i] < arr[i-1] and arrIsDescending == True: # first adjacent non-equal element resulted in descending order. Current adjacent elements are in ascending order.
                return False
    return True

# assert(IsArraySorted([1,2,3,4,5,6,7,8,9,10]) == True), "IsArraySorted([1,2,3,4,5,6,7,8,9,10]) == True failed"
# assert(IsArraySorted([10,9,8,7,6,5,4,3,2,1]) == True), "IsArraySorted([10,9,8,7,6,5,4,3,2,1]) == True failed"
# assert(IsArraySorted([1,2,3,5,4,6,7,8,9,10]) == False), "IsArraySorted([1,2,3,5,4,6,7,8,9,10]) == False failed"
# assert(IsArraySorted([10,9,8,6,7,5,4,3,2,1]) == False), "IsArraySorted([10,9,8,6,7,5,4,3,2,1]) == False failed"
# assert(IsArraySorted([1,1,1,1,1,1,1]) == True), "IsArraySorted([1,1,1,1,1,1,1]) == True failed"


def ReverseArrayInPlace(arr): # O(n) time complexity, O(1) space complexity - reverses the array in place
    n = len(arr)
    for iter in range(n//2):
        # print(f"swapping arr[{iter}]={arr[iter]} and arr[{n - iter -1}]={arr[n - iter -1]}")
        arr[iter], arr[n-iter-1] = arr[n-iter-1], arr[iter]
    return arr

# assert(ReverseArrayInPlace([1,2,3,4,5]) == [5,4,3,2,1]), "ReverseArrayInPlace([1,2,3,4,5]) == [5,4,3,2,1] failed"
# assert(ReverseArrayInPlace([1,2,3,4,5,6]) == [6,5,4,3,2,1]), "ReverseArrayInPlace([1,2,3,4,5,6]) == [6,5,4,3,2,1] failed"


def MoveZerosToTheEnd(arr):
    zeroIndex = None
    #print(f"source array: {arr}")
    for iter in range(len(arr)):
        if zeroIndex is None:
            if arr[iter] == 0:
                zeroIndex = iter
            else:
                continue # move to next iteration
        if arr[iter] !=0:
            arr[zeroIndex], arr[iter] = arr[iter], arr[zeroIndex]
            zeroIndex += 1 # the non-zero one will be always the first one after current zero or all the next zeros
    #print(f"response  array: {arr}")
    return arr

# assert(MoveZerosToTheEnd([0,1,0,3,12]) == [1,3,12,0,0]), "MoveZerosToTheEnd([0,1,0,3,12]) == [1,3,12,0,0] failed"
# assert(MoveZerosToTheEnd([0,0,1]) == [1,0,0]), "MoveZerosToTheEnd([0,0,1]) == [1,0,0] failed"

def CounterClockWiseRotate(arr): # O(n) time complexity, O(1) space complexity - rotates the array counter clockwise by one position
    # print(f"source array: {arr}")
    assert(len(arr) > 0), "Array must have at least one element"
    n = len(arr)
    temp = arr[0]
    for iter in range(1, n):
        # print(f"sending arr[{iter}]={arr[iter]} to arr[{iter-1}]={arr[iter-1]}")
        arr[iter-1] = arr[iter]
    arr[n-1]= temp
    # print(f"response  array: {arr}")
    return arr

#assert(CounterClockWiseRotate([1,2,3,4,5]) == [2,3,4,5,1]), "CounterClockWiseRotate([1,2,3,4,5]) == [2,3,4,5,1] failed"
#assert(CounterClockWiseRotate([5,4,3,2,1]) == [4,3,2,1,5]), "CounterClockWiseRotate([5,4,3,2,1]) == [4,3,2,1,5] failed"

def CounterClockWiseRotateBymSpaces(arr,m): # O(n) runtime complexity and O(1) space complexity
    temp = arr[-m:]
    # print(f"temp={temp},arr={arr}")
    n = len(arr)
    for iter in range(n-m):
        arr[iter-m] = arr[iter]
    tmp=0
    for iter1 in range(n-m,n):
        #print(f"iter1-m={iter1-m}, iter1={iter1}")
        arr[iter1-m] = temp[tmp]
        tmp+=1
    #print(f"response  array: {arr}")
    return arr

#assert(CounterClockWiseRotateBymSpaces([1,2,3,4,5,6,7,8],3) == [4,5,6,7,8,1,2,3])
#assert(CounterClockWiseRotate([5,4,3,2,1]) == [4,3,2,1,5]), "CounterClockWiseRotate([5,4,3,2,1]) == [4,3,2,1,5] failed"

'''
leader in an array (sorted or unsorted) is a number which does not have anything greater than it on right of the array.
Ex - for array [7,10,4,3,6,5,2] the answer is 10,6,5,2
Ruick solution I could think of  -  traverse from end of array noting the greatest number hit so far ('greatest_so_far'). 
If current number is greater than the greatest_so_far then it belongs to the answer. and greatest_so_far becomes current number
'''
def PrintLeadersInAnArray(arr): 
    n = len(arr)
    greatest_so_far = arr[n-1]
    response = []
    response.append(greatest_so_far)
    for y in reversed(range(n-1)):
        if arr[y]>=greatest_so_far:
            response.append(arr[y])
            greatest_so_far = arr[y]
    response.reverse()
    # print(f"response  array: {response}")
    return response

# assert(PrintLeadersInAnArray([7,10,4,3,6,5,2]) == [10,6,5,2])
# assert(PrintLeadersInAnArray([10,20,30]) == [30])
# assert(PrintLeadersInAnArray([30,20,10]) == [30,20,10])

        
